// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ampare_backend.Models;

#nullable disable

namespace ampare_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231123214106_removendo-tabela-usuarios")]
    partial class removendotabelausuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ampare_backend.Models.Cadastro", b =>
                {
                    b.Property<int>("IdCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCadastro"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCadastro");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("ampare_backend.Models.Projeto", b =>
                {
                    b.Property<int>("IdProjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProjeto"), 1L, 1);

                    b.Property<int?>("CadastroOngIdCadastro")
                        .HasColumnType("int");

                    b.Property<string>("CidadeProjeto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoProjeto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoProjeto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOng")
                        .HasColumnType("int");

                    b.Property<string>("NomeProjeto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsavelProjeto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusProjeto")
                        .HasColumnType("bit");

                    b.HasKey("IdProjeto");

                    b.HasIndex("CadastroOngIdCadastro");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("CadastroVoluntarioProjeto", b =>
                {
                    b.Property<int>("ProjetosIdProjeto")
                        .HasColumnType("int");

                    b.Property<int>("VoluntariosIdCadastro")
                        .HasColumnType("int");

                    b.HasKey("ProjetosIdProjeto", "VoluntariosIdCadastro");

                    b.HasIndex("VoluntariosIdCadastro");

                    b.ToTable("CadastroVoluntarioProjeto");
                });

            modelBuilder.Entity("ampare_backend.Models.CadastroOng", b =>
                {
                    b.HasBaseType("ampare_backend.Models.Cadastro");

                    b.ToTable("Ongs", (string)null);
                });

            modelBuilder.Entity("ampare_backend.Models.CadastroVoluntario", b =>
                {
                    b.HasBaseType("ampare_backend.Models.Cadastro");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.ToTable("Voluntarios", (string)null);
                });

            modelBuilder.Entity("ampare_backend.Models.Projeto", b =>
                {
                    b.HasOne("ampare_backend.Models.CadastroOng", "CadastroOng")
                        .WithMany("Projetos")
                        .HasForeignKey("CadastroOngIdCadastro");

                    b.Navigation("CadastroOng");
                });

            modelBuilder.Entity("CadastroVoluntarioProjeto", b =>
                {
                    b.HasOne("ampare_backend.Models.Projeto", null)
                        .WithMany()
                        .HasForeignKey("ProjetosIdProjeto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ampare_backend.Models.CadastroVoluntario", null)
                        .WithMany()
                        .HasForeignKey("VoluntariosIdCadastro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ampare_backend.Models.CadastroOng", b =>
                {
                    b.HasOne("ampare_backend.Models.Cadastro", null)
                        .WithOne()
                        .HasForeignKey("ampare_backend.Models.CadastroOng", "IdCadastro")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ampare_backend.Models.CadastroVoluntario", b =>
                {
                    b.HasOne("ampare_backend.Models.Cadastro", null)
                        .WithOne()
                        .HasForeignKey("ampare_backend.Models.CadastroVoluntario", "IdCadastro")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ampare_backend.Models.CadastroOng", b =>
                {
                    b.Navigation("Projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
